exclude: ^vendor/.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
      - id: go-mod-tidy
      - id: go-mod-vendor

  # How do I disable the linter when a false positive is occurring?
  # https://golangci-lint.run/usage/false-positives/#nolint-directive
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.0.0
    hooks:
      - name: golangci-lint-full
        id: golangci-lint-full
        language_version: "1.24.5"
        args: [--build-tags, "scheduler"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        # Why '--strict'? To return a non-zero exit code on warnings
        # so pre-commit captures it as a failure.
        args: [--strict, --config-file, .yamllint]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-fix
        exclude: |
          (?x)^(
          db/schema.sql|
          .*/?testdata/
          )

  - repo: local
    hooks:
      # https://github.com/hadolint/hadolint
      - id: dockerfile-lint
        name: Dockerfile Lint
        language: docker_image
        entry: hadolint/hadolint:v2.12.0 hadolint
        files: ^.*Dockerfile.*$

        # https://github.com/koalaman/shellcheck
      - id: shellcheck-lint
        name: Shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.9.0
        types: [shell]

        # https://github.com/igorshubovych/markdownlint-cli
      - id: markdown-lint
        name: Markdown Lint
        language: docker_image
        entry: ghcr.io/igorshubovych/markdownlint-cli:v0.32.2
        args: [--config, .markdownlintrc, --fix]
        types: [markdown]
