// Package scheduler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package scheduler

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CourseInterval.
const (
	CourseIntervalBiWeekly CourseInterval = "bi-weekly"
	CourseIntervalMonthly  CourseInterval = "monthly"
	CourseIntervalWeekly   CourseInterval = "weekly"
)

// Defines values for CourseUpdateInterval.
const (
	CourseUpdateIntervalBiWeekly CourseUpdateInterval = "bi-weekly"
	CourseUpdateIntervalMonthly  CourseUpdateInterval = "monthly"
	CourseUpdateIntervalWeekly   CourseUpdateInterval = "weekly"
)

// Defines values for TrackerStatus.
const (
	Fulfilled   TrackerStatus = "fulfilled"
	Scheduled   TrackerStatus = "scheduled"
	Skipped     TrackerStatus = "skipped"
	Unscheduled TrackerStatus = "unscheduled"
)

// Defines values for UserRole.
const (
	UserRoleAdmin   UserRole = "Admin"
	UserRoleStudent UserRole = "Student"
	UserRoleTutor   UserRole = "Tutor"
)

// Defines values for UserUpdateRole.
const (
	UserUpdateRoleAdmin   UserUpdateRole = "Admin"
	UserUpdateRoleStudent UserUpdateRole = "Student"
	UserUpdateRoleTutor   UserUpdateRole = "Tutor"
)

// Availability defines model for Availability.
type Availability struct {
	AvailableTimeIntervals []TimeInterval `json:"available_time_intervals"`
	UserId                 string         `json:"user_id"`
}

// AvailabilityChanges defines model for AvailabilityChanges.
type AvailabilityChanges struct {
	Add    *[]TimeInterval `json:"add,omitempty"`
	Remove *[]TimeInterval `json:"remove,omitempty"`
}

// AvailabilityUpdate defines model for AvailabilityUpdate.
type AvailabilityUpdate struct {
	Changes AvailabilityChanges `json:"changes"`
	UserId  string              `json:"user_id"`
}

// BatchAvailabilityRequest defines model for BatchAvailabilityRequest.
type BatchAvailabilityRequest struct {
	UserIds []string `json:"user_ids"`
}

// Class defines model for Class.
type Class struct {
	ClassId  string  `json:"class_id"`
	CourseId *string `json:"course_id,omitempty"`

	// Duration Duration in minutes
	Duration int       `json:"duration"`
	Start    time.Time `json:"start"`
	Students []string  `json:"students"`
	Teachers []string  `json:"teachers"`
}

// Course defines model for Course.
type Course struct {
	CourseDescription *string        `json:"course_description,omitempty"`
	CourseId          string         `json:"course_id"`
	CourseName        string         `json:"course_name"`
	EndAt             time.Time      `json:"end_at"`
	Frequency         int            `json:"frequency"`
	Interval          CourseInterval `json:"interval"`
	StartAt           time.Time      `json:"start_at"`
	Students          []string       `json:"students"`
	Tutors            []string       `json:"tutors"`
}

// CourseInterval defines model for Course.Interval.
type CourseInterval string

// CourseClassesRequest defines model for CourseClassesRequest.
type CourseClassesRequest struct {
	CourseId string `json:"course_id"`
}

// CourseParticipantChanges defines model for CourseParticipantChanges.
type CourseParticipantChanges struct {
	Add    *[]string `json:"add,omitempty"`
	Remove *[]string `json:"remove,omitempty"`
}

// CourseTrackersRequest defines model for CourseTrackersRequest.
type CourseTrackersRequest struct {
	CourseId string `json:"course_id"`
}

// CourseUpdate defines model for CourseUpdate.
type CourseUpdate struct {
	CourseName *string                   `json:"course_name,omitempty"`
	EndAt      *time.Time                `json:"end_at,omitempty"`
	Frequency  *int                      `json:"frequency,omitempty"`
	Interval   *CourseUpdateInterval     `json:"interval,omitempty"`
	StartAt    *time.Time                `json:"start_at,omitempty"`
	Students   *CourseParticipantChanges `json:"students,omitempty"`
	Teachers   *CourseParticipantChanges `json:"teachers,omitempty"`
}

// CourseUpdateInterval defines model for CourseUpdate.Interval.
type CourseUpdateInterval string

// Organization defines model for Organization.
type Organization struct {
	Name           string `json:"name"`
	OrganizationId string `json:"organization_id"`
}

// TimeInterval defines model for TimeInterval.
type TimeInterval = []time.Time

// Tracker defines model for Tracker.
type Tracker struct {
	// Completed Array of class IDs
	Completed   []string  `json:"completed"`
	CourseId    string    `json:"course_id"`
	PeriodEnd   time.Time `json:"period_end"`
	PeriodStart time.Time `json:"period_start"`
	Required    int       `json:"required"`

	// Scheduled Array of class IDs
	Scheduled  []string      `json:"scheduled"`
	Status     TrackerStatus `json:"status"`
	TrackingId string        `json:"tracking_id"`
}

// TrackerStatus defines model for Tracker.Status.
type TrackerStatus string

// User defines model for User.
type User struct {
	Courses     *[]string            `json:"courses,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   string               `json:"first_name"`
	LastName    string               `json:"last_name"`
	OrgId       string               `json:"org_id"`
	PhoneNumber *string              `json:"phone_number,omitempty"`
	Role        UserRole             `json:"role"`
	UserId      string               `json:"user_id"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserClassesRequest defines model for UserClassesRequest.
type UserClassesRequest struct {
	UserId string `json:"user_id"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Email       *openapi_types.Email `json:"email,omitempty"`
	FirstName   *string              `json:"first_name,omitempty"`
	LastName    *string              `json:"last_name,omitempty"`
	PhoneNumber *string              `json:"phone_number,omitempty"`
	Role        *UserUpdateRole      `json:"role,omitempty"`
}

// UserUpdateRole defines model for UserUpdate.Role.
type UserUpdateRole string

// GetV1AvailabilityJSONRequestBody defines body for GetV1Availability for application/json ContentType.
type GetV1AvailabilityJSONRequestBody = BatchAvailabilityRequest

// PostV1ClassJSONRequestBody defines body for PostV1Class for application/json ContentType.
type PostV1ClassJSONRequestBody = Class

// GetV1ClassCourseJSONRequestBody defines body for GetV1ClassCourse for application/json ContentType.
type GetV1ClassCourseJSONRequestBody = CourseClassesRequest

// GetV1ClassUserJSONRequestBody defines body for GetV1ClassUser for application/json ContentType.
type GetV1ClassUserJSONRequestBody = UserClassesRequest

// PostV1CourseJSONRequestBody defines body for PostV1Course for application/json ContentType.
type PostV1CourseJSONRequestBody = Course

// PostV1CourseCourseIdJSONRequestBody defines body for PostV1CourseCourseId for application/json ContentType.
type PostV1CourseCourseIdJSONRequestBody = CourseUpdate

// PostV1OrgOrgIdJSONRequestBody defines body for PostV1OrgOrgId for application/json ContentType.
type PostV1OrgOrgIdJSONRequestBody = Organization

// GetV1TrackersCourseJSONRequestBody defines body for GetV1TrackersCourse for application/json ContentType.
type GetV1TrackersCourseJSONRequestBody = CourseTrackersRequest

// PatchV1UserUserIdJSONRequestBody defines body for PatchV1UserUserId for application/json ContentType.
type PatchV1UserUserIdJSONRequestBody = UserUpdate

// PostV1UserUserIdJSONRequestBody defines body for PostV1UserUserId for application/json ContentType.
type PostV1UserUserIdJSONRequestBody = User

// PatchV1UserUserIdAvailabilityJSONRequestBody defines body for PatchV1UserUserIdAvailability for application/json ContentType.
type PatchV1UserUserIdAvailabilityJSONRequestBody = AvailabilityUpdate

// PostV1UserUserIdAvailabilityJSONRequestBody defines body for PostV1UserUserIdAvailability for application/json ContentType.
type PostV1UserUserIdAvailabilityJSONRequestBody = Availability
