// Package scheduler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package scheduler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get availability for multiple users (batch)
	// (GET /v1/availability)
	GetBatchAvailability(c *gin.Context)
	// Create a new class
	// (POST /v1/class)
	CreateClass(c *gin.Context)
	// List classes for a course
	// (GET /v1/class/course)
	ListCourseClasses(c *gin.Context)
	// List classes for a user
	// (GET /v1/class/user)
	ListUserClasses(c *gin.Context)
	// Get all courses
	// (GET /v1/course)
	ListCourses(c *gin.Context)
	// Create a new course
	// (POST /v1/course)
	CreateCourse(c *gin.Context)
	// Get a course by ID
	// (GET /v1/course/{course_id})
	GetCourse(c *gin.Context, courseId string)
	// Update a course
	// (POST /v1/course/{course_id})
	UpdateCourse(c *gin.Context, courseId string)
	// Delete an organization
	// (DELETE /v1/org/{org_id})
	DeleteOrg(c *gin.Context, orgId string)
	// Create a new organization
	// (POST /v1/org/{org_id})
	CreateOrg(c *gin.Context, orgId string)
	// Get trackers for a course
	// (GET /v1/trackers/course)
	GetTrackers(c *gin.Context)
	// Get all users
	// (GET /v1/user)
	ListUsers(c *gin.Context)
	// Delete a user
	// (DELETE /v1/user/{user_id})
	DeleteUser(c *gin.Context, userId string)
	// Get a user by ID
	// (GET /v1/user/{user_id})
	GetUser(c *gin.Context, userId string)
	// Update a user
	// (PATCH /v1/user/{user_id})
	UpdateUser(c *gin.Context, userId string)
	// Create a new user
	// (POST /v1/user/{user_id})
	CreateUser(c *gin.Context, userId string)
	// Get availability for a user
	// (GET /v1/user/{user_id}/availability)
	GetAvailability(c *gin.Context, userId string)
	// Update availability for a user
	// (PATCH /v1/user/{user_id}/availability)
	UpdateAvailability(c *gin.Context, userId string)
	// Create availability for a user
	// (POST /v1/user/{user_id}/availability)
	CreateAvailability(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetBatchAvailability operation middleware
func (siw *ServerInterfaceWrapper) GetBatchAvailability(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBatchAvailability(c)
}

// CreateClass operation middleware
func (siw *ServerInterfaceWrapper) CreateClass(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateClass(c)
}

// ListCourseClasses operation middleware
func (siw *ServerInterfaceWrapper) ListCourseClasses(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCourseClasses(c)
}

// ListUserClasses operation middleware
func (siw *ServerInterfaceWrapper) ListUserClasses(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUserClasses(c)
}

// ListCourses operation middleware
func (siw *ServerInterfaceWrapper) ListCourses(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCourses(c)
}

// CreateCourse operation middleware
func (siw *ServerInterfaceWrapper) CreateCourse(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCourse(c)
}

// GetCourse operation middleware
func (siw *ServerInterfaceWrapper) GetCourse(c *gin.Context) {

	var err error

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", c.Param("course_id"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter course_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCourse(c, courseId)
}

// UpdateCourse operation middleware
func (siw *ServerInterfaceWrapper) UpdateCourse(c *gin.Context) {

	var err error

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", c.Param("course_id"), &courseId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter course_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCourse(c, courseId)
}

// DeleteOrg operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrg(c *gin.Context) {

	var err error

	// ------------- Path parameter "org_id" -------------
	var orgId string

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", c.Param("org_id"), &orgId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter org_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOrg(c, orgId)
}

// CreateOrg operation middleware
func (siw *ServerInterfaceWrapper) CreateOrg(c *gin.Context) {

	var err error

	// ------------- Path parameter "org_id" -------------
	var orgId string

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", c.Param("org_id"), &orgId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter org_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrg(c, orgId)
}

// GetTrackers operation middleware
func (siw *ServerInterfaceWrapper) GetTrackers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrackers(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUser(c, userId)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUser(c, userId)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, userId)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c, userId)
}

// GetAvailability operation middleware
func (siw *ServerInterfaceWrapper) GetAvailability(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAvailability(c, userId)
}

// UpdateAvailability operation middleware
func (siw *ServerInterfaceWrapper) UpdateAvailability(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAvailability(c, userId)
}

// CreateAvailability operation middleware
func (siw *ServerInterfaceWrapper) CreateAvailability(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAvailability(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/availability", wrapper.GetBatchAvailability)
	router.POST(options.BaseURL+"/v1/class", wrapper.CreateClass)
	router.GET(options.BaseURL+"/v1/class/course", wrapper.ListCourseClasses)
	router.GET(options.BaseURL+"/v1/class/user", wrapper.ListUserClasses)
	router.GET(options.BaseURL+"/v1/course", wrapper.ListCourses)
	router.POST(options.BaseURL+"/v1/course", wrapper.CreateCourse)
	router.GET(options.BaseURL+"/v1/course/:course_id", wrapper.GetCourse)
	router.POST(options.BaseURL+"/v1/course/:course_id", wrapper.UpdateCourse)
	router.DELETE(options.BaseURL+"/v1/org/:org_id", wrapper.DeleteOrg)
	router.POST(options.BaseURL+"/v1/org/:org_id", wrapper.CreateOrg)
	router.GET(options.BaseURL+"/v1/trackers/course", wrapper.GetTrackers)
	router.GET(options.BaseURL+"/v1/user", wrapper.ListUsers)
	router.DELETE(options.BaseURL+"/v1/user/:user_id", wrapper.DeleteUser)
	router.GET(options.BaseURL+"/v1/user/:user_id", wrapper.GetUser)
	router.PATCH(options.BaseURL+"/v1/user/:user_id", wrapper.UpdateUser)
	router.POST(options.BaseURL+"/v1/user/:user_id", wrapper.CreateUser)
	router.GET(options.BaseURL+"/v1/user/:user_id/availability", wrapper.GetAvailability)
	router.PATCH(options.BaseURL+"/v1/user/:user_id/availability", wrapper.UpdateAvailability)
	router.POST(options.BaseURL+"/v1/user/:user_id/availability", wrapper.CreateAvailability)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaXW/bNhf+KwTf92ID1Nj9uBh8lzZAYWBAi7W9KoKAkY5tthKpkpQ7L/B/H/ghmZRJ",
	"W3asdN3uYlE6POd5zjfygHNe1ZwBUxLPHrDMV1AR8+f1mtCS3NOSqo3+XQteg1AUzCmxpyXcKVrBHWUK",
	"xJqU5owqqMwf/xewwDP8v8nukom7YfKRVjB3X+FthtWmBjzDRAiy0b8bCeKOFlqMO5JKULbE222GBXxr",
	"qIACzz53L2ZpnW478fz+C+RKy/fNe7MibGnt6llZFBczSEDF13AhcdsjFn2qC6Jg36B8Z+mhy2PgnMdJ",
	"e2GMgtdE5Sv/qj/gWwNS7avt5IXe1VMhAlFEpbgmb0oiI/Tn+nHc4AznvBESUqdFI4iinOnDAmQuaG1/",
	"4ht3gihDFWWNAok7lbTPLkFoCVIRYaBYcFERhWdYU/pMu/bu/d2FUjVFG8VDIcqwApKvQDwG2A6kVmXP",
	"eE8t764oAwbNCAUW5QDCk8lwp4xUED0HVtyRE7BeaPuB5RtPmsdcm3j0KbCm0ih9B/habnCGK87Uyvx1",
	"T5+5p7dRPolQJ2l1pgc0ij+O/w76EOiQe3uLZ1aHuoeXj2zaSUywgkwmi0O+kNQ9fd17IhTNaU2YGlwn",
	"jqIeKQbHUU8o+FGQ/CuIJwMkWVv+c1F2qIQmnaeXdc+TEfOGd2JJGP2rKzshO0lauPfZIB/pf5BZ2TGH",
	"CZoY39mHYV2RP+f2ixcZrijb/ejHk4uBmFNWdQkKiv1CfK0/RnyBTAVD8xudn4aH8OGSU4OgvLgDVgw3",
	"131zYuHfUROLEu1KRVOOYL9URDXSj75FUy5oqe/y781ww/xf8iutayii4ag0jZQtB/mh/3IWlKEAyIAL",
	"T0Ko485POstiDv1Jxp1M331i4YWK0DKg2T6JZUIqpEon1pIcOuVimXTSFWdwx5rq3lq171u8BJ/h66Ki",
	"uqv7YJMgzvBHXdijXJ4xLDhVA4N985xCKWKONQYna5S6KFUBn4rSEXnbLyxbU2sXPJJA3s/RggtUEUaW",
	"lC2Rq42IsAKZjg+5ENOiM6yo0mrhDy7uBLp+P8cZXoOQVuLzq+nV1DhtDYzUFM/wy6vp1UsdxEStDMiT",
	"9fMJ6e0mlmDo1lyYsjQv8Ay/BbU3YboEAFK95sXGxi5TGhLdxdV1SXMjYPJF2iJqS/GxQp2cZLehaynR",
	"gHkga85cxngxnZ6kx6DtQWDzfi+pB9SASmMA8mFFBVHE+INsqoqIjUU0fMew35SK1iUgHTUS/XKvRf2q",
	"6SZLaZzP1+VWS9QU5t3IzWWEvDcCiLKt/kicWdmDCHq+7/vma5QbLQskmzwHKRdNWRq4X1lO+xgXSHR+",
	"4eNqjUUEMfhuq7EHn9UzxG2Sd+Ny1PV/p1IFw9JYGMYGsh/l847Q485utbZAu2Z6x4WGrj0y/k2QA/sI",
	"JY1rDZKEeCVqJDoiRfAfT4bWeTgVBuQ0EUOjwhIwOgZWnQEgGEt1J+60i6TdsuxOPfvtDbe6JziURlsH",
	"Hi8HnJ9IXTCOkUn34raFK/CXyUM3O2wPNRMdijURpAJlBvjPD5hqlXR70k7Cs2AYCTHJPFT7rdftI51y",
	"KEtRAgpQhJbSYv4qyRPjCi14w4qYjzrE0f0GzW9OcVPbUD8NwGNFgBsKhifcKL6NkRKLg9M5sRpFC1gv",
	"ELhYTh7s9LW11+hZeJ+nG/P8nVgOIqkb5x4TAhGz/UUXsqoOBCz4MgWbNRIRhvxNl4desGg7lnvHBuvy",
	"7hyYd25aD5AeI7kP48b5t3Ir8mMdwltQ7TZ91GrZX9n/qC6tXZsOb5pbJCPpvz1Kdc3tZR0rgzrmp2nV",
	"zF7vhEbNzLqJNq1xWrd2G9mB0ZMHt2EakGw/2Y73eALZrdEunG5Nh35SmjVfHEuv/V7ewZQlI/OJkZhe",
	"dCxLjj7H+q6DWNquS9u713N1cNZE5atUyzU+puNMuY9stgyoJ7VaB2noGq2USx9qEH5WCs5uDezEP0JL",
	"EEc/mncHb5B7y+OfL/mEm+BEEiK9dfGZmai/Gt4LiN4q+EhyejrsLx8hkX/GOzdZ+aJGSFpnkHYgm/1b",
	"ODs7uwVsXTjLnUqVkQJi3cLf62V5TkpUwBpKXlfAFLLv4gw3osQzvFKqnk0mpX5vxaWa/TadTvH2dvt3",
	"AAAA//9hUbvmNiwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
